// Package fieldvalue provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package fieldvalue

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Details *[]struct {
		ExpectedType *string `json:"expected_type,omitempty"`
		Field        *string `json:"field,omitempty"`
		Got          *string `json:"got,omitempty"`
	} `json:"details,omitempty"`
	Error string `json:"error"`
}

// FieldDefinition defines model for FieldDefinition.
type FieldDefinition struct {
	Key      string `json:"key"`
	Required bool   `json:"required"`
	Type     string `json:"type"`
}

// FieldRecord defines model for FieldRecord.
type FieldRecord struct {
	CreatedAt   time.Time              `json:"created_at"`
	ProjectSlug string                 `json:"project_slug"`
	RecordId    openapi_types.UUID     `json:"record_id"`
	SchemaKey   string                 `json:"schema_key"`
	UpdatedAt   time.Time              `json:"updated_at"`
	Values      map[string]interface{} `json:"values"`
}

// FilterNode defines model for FilterNode.
type FilterNode struct {
	Conditions *[]FilterNode `json:"conditions,omitempty"`
	Field      *string       `json:"field,omitempty"`
	Op         string        `json:"op"`
	Value      interface{}   `json:"value"`
}

// MutateRequest defines model for MutateRequest.
type MutateRequest struct {
	DeleteRecord *bool                   `json:"delete_record,omitempty"`
	RecordId     *openapi_types.UUID     `json:"record_id,omitempty"`
	SchemaKey    string                  `json:"schema_key"`
	Values       *map[string]interface{} `json:"values,omitempty"`
}

// QueryRequest defines model for QueryRequest.
type QueryRequest struct {
	Filter    *FilterNode `json:"filter,omitempty"`
	SchemaKey string      `json:"schema_key"`
}

// QueryResponse defines model for QueryResponse.
type QueryResponse struct {
	Records []FieldRecord `json:"records"`
}

// SchemaDefinition defines model for SchemaDefinition.
type SchemaDefinition struct {
	Fields      []FieldDefinition `json:"fields"`
	ProjectSlug string            `json:"project_slug"`
	SchemaKey   string            `json:"schema_key"`
}

// GetFieldValueDefinitionParams defines parameters for GetFieldValueDefinition.
type GetFieldValueDefinitionParams struct {
	ProjectSlug string `form:"project_slug" json:"project_slug"`
	SchemaKey   string `form:"schema_key" json:"schema_key"`
}

// MutateFieldValueParams defines parameters for MutateFieldValue.
type MutateFieldValueParams struct {
	ProjectSlug string `form:"project_slug" json:"project_slug"`
}

// QueryFieldValuesParams defines parameters for QueryFieldValues.
type QueryFieldValuesParams struct {
	ProjectSlug string `form:"project_slug" json:"project_slug"`
}

// MutateFieldValueJSONRequestBody defines body for MutateFieldValue for application/json ContentType.
type MutateFieldValueJSONRequestBody = MutateRequest

// QueryFieldValuesJSONRequestBody defines body for QueryFieldValues for application/json ContentType.
type QueryFieldValuesJSONRequestBody = QueryRequest
