/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List schemas for a project */
        get: operations["listSchemas"];
        put?: never;
        /** Create a new schema */
        post: operations["createSchema"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schemas/{schemaKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a schema with its fields */
        get: operations["getSchema"];
        put?: never;
        post?: never;
        /** Delete a schema */
        delete: operations["deleteSchema"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schemas/{schemaKey}/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a field to a schema */
        post: operations["createSchemaField"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schemas/{schemaKey}/fields/{fieldKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a field from a schema */
        delete: operations["deleteSchemaField"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Schema: {
            project_slug: string;
            key: string;
            name: string;
            /** Format: int64 */
            created_by: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        SchemaWithFields: components["schemas"]["Schema"] & {
            fields?: components["schemas"]["SchemaField"][];
        };
        SchemaField: {
            key: string;
            type: components["schemas"]["FieldType"];
            /** Format: int64 */
            created_by: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @enum {string} */
        FieldType: "string" | "int" | "float" | "boolean" | "date" | "datetime";
        CreateSchemaRequest: {
            project_slug: string;
            key: string;
            name: string;
        };
        CreateSchemaFieldRequest: {
            key: string;
            type: components["schemas"]["FieldType"];
        };
        ErrorResponse: {
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSchemas: {
        parameters: {
            query: {
                project_slug: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of schemas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schema"][];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createSchema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSchemaRequest"];
            };
        };
        responses: {
            /** @description Schema created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schema"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Schema already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSchema: {
        parameters: {
            query: {
                project_slug: string;
            };
            header?: never;
            path: {
                schemaKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schema found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaWithFields"];
                };
            };
            /** @description Schema not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteSchema: {
        parameters: {
            query: {
                project_slug: string;
            };
            header?: never;
            path: {
                schemaKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schema deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Schema not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createSchemaField: {
        parameters: {
            query: {
                project_slug: string;
            };
            header?: never;
            path: {
                schemaKey: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSchemaFieldRequest"];
            };
        };
        responses: {
            /** @description Field created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaField"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Schema not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Field already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteSchemaField: {
        parameters: {
            query: {
                project_slug: string;
            };
            header?: never;
            path: {
                schemaKey: string;
                fieldKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Field deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Schema or field not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
