/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/field-values/mutate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create, update, or delete a record and its field values */
        post: operations["mutateFieldValue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/field-values/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query records by schema with optional filter AST */
        post: operations["queryFieldValues"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/field-values/definition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Introspection endpoint returning schema field definitions */
        get: operations["getFieldValueDefinition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FieldRecord: {
            /** Format: uuid */
            record_id: string;
            schema_key: string;
            project_slug: string;
            values: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        MutateRequest: {
            schema_key: string;
            /** Format: uuid */
            record_id?: string;
            values?: {
                [key: string]: unknown;
            };
            delete_record?: boolean;
        };
        QueryRequest: {
            schema_key: string;
            filter?: components["schemas"]["FilterNode"];
        };
        QueryResponse: {
            records: components["schemas"]["FieldRecord"][];
        };
        FilterNode: {
            op: string;
            field?: string;
            value?: unknown;
            conditions?: components["schemas"]["FilterNode"][];
        };
        SchemaDefinition: {
            schema_key: string;
            project_slug: string;
            fields: components["schemas"]["FieldDefinition"][];
        };
        FieldDefinition: {
            key: string;
            type: string;
            required: boolean;
        };
        ErrorResponse: {
            error: string;
            details?: {
                field?: string;
                expected_type?: string;
                got?: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    mutateFieldValue: {
        parameters: {
            query: {
                project_slug: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MutateRequest"];
            };
        };
        responses: {
            /** @description Record updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldRecord"];
                };
            };
            /** @description Record created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldRecord"];
                };
            };
            /** @description Record deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request or validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Schema or record not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    queryFieldValues: {
        parameters: {
            query: {
                project_slug: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Query results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Invalid request or filter AST */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Schema not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getFieldValueDefinition: {
        parameters: {
            query: {
                project_slug: string;
                schema_key: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schema definition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaDefinition"];
                };
            };
            /** @description Schema not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
