root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -buildvcs=false -o ./tmp/fieldservice ./cmd/fieldservice"
bin = "./tmp/fieldservice"
delay = 1000
exclude_dir = ["web", "docs", "keycloak", "infra", "build", "tmp", "proto"]
exclude_regex = ["_test\\.go"]
include_ext = ["go"]
