// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for FieldType.
const (
	Boolean  FieldType = "boolean"
	Date     FieldType = "date"
	Datetime FieldType = "datetime"
	Float    FieldType = "float"
	Int      FieldType = "int"
	String   FieldType = "string"
)

// CreateSchemaFieldRequest defines model for CreateSchemaFieldRequest.
type CreateSchemaFieldRequest struct {
	Key  string    `json:"key"`
	Type FieldType `json:"type"`
}

// CreateSchemaRequest defines model for CreateSchemaRequest.
type CreateSchemaRequest struct {
	Key         string `json:"key"`
	Name        string `json:"name"`
	ProjectSlug string `json:"project_slug"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// FieldType defines model for FieldType.
type FieldType string

// Schema defines model for Schema.
type Schema struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedBy   int64     `json:"created_by"`
	Key         string    `json:"key"`
	Name        string    `json:"name"`
	ProjectSlug string    `json:"project_slug"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// SchemaField defines model for SchemaField.
type SchemaField struct {
	CreatedAt time.Time `json:"created_at"`
	CreatedBy int64     `json:"created_by"`
	Key       string    `json:"key"`
	Type      FieldType `json:"type"`
	UpdatedAt time.Time `json:"updated_at"`
}

// SchemaWithFields defines model for SchemaWithFields.
type SchemaWithFields struct {
	CreatedAt   time.Time      `json:"created_at"`
	CreatedBy   int64          `json:"created_by"`
	Fields      *[]SchemaField `json:"fields,omitempty"`
	Key         string         `json:"key"`
	Name        string         `json:"name"`
	ProjectSlug string         `json:"project_slug"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

// ListSchemasParams defines parameters for ListSchemas.
type ListSchemasParams struct {
	ProjectSlug string `form:"project_slug" json:"project_slug"`
}

// DeleteSchemaParams defines parameters for DeleteSchema.
type DeleteSchemaParams struct {
	ProjectSlug string `form:"project_slug" json:"project_slug"`
}

// GetSchemaParams defines parameters for GetSchema.
type GetSchemaParams struct {
	ProjectSlug string `form:"project_slug" json:"project_slug"`
}

// CreateSchemaFieldParams defines parameters for CreateSchemaField.
type CreateSchemaFieldParams struct {
	ProjectSlug string `form:"project_slug" json:"project_slug"`
}

// DeleteSchemaFieldParams defines parameters for DeleteSchemaField.
type DeleteSchemaFieldParams struct {
	ProjectSlug string `form:"project_slug" json:"project_slug"`
}

// CreateSchemaJSONRequestBody defines body for CreateSchema for application/json ContentType.
type CreateSchemaJSONRequestBody = CreateSchemaRequest

// CreateSchemaFieldJSONRequestBody defines body for CreateSchemaField for application/json ContentType.
type CreateSchemaFieldJSONRequestBody = CreateSchemaFieldRequest
