root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -buildvcs=false -o ./tmp/proxy ./cmd/proxy"
bin = "./tmp/proxy"
delay = 1000
exclude_dir = ["web", "docs", "keycloak", "infra", "build", "tmp", "proto"]
exclude_regex = ["_test\\.go"]
include_ext = ["go"]
